## .unqiue(),.nunique() Functions

In [1]:
# The pandas series object represents a single-column data or a set of observations related to a single variable

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('Location.csv', squeeze= True)
location_data = data.copy()
location_data.head()

C:\Users\Sourav Vishwakarma\AppData\Local\Temp\ipykernel_6880\4004024906.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  data = pd.read_csv('Location.csv', squeeze= True)


0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [4]:
type(location_data)

pandas.core.series.Series

In [5]:
# Overview of data
location_data.describe()

count            1043
unique            296
top       Location 25
freq               31
Name: Location, dtype: object

In [6]:
# Overview of Data object
location_data.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1043 entries, 0 to 1042
Series name: Location
Non-Null Count  Dtype 
--------------  ----- 
1043 non-null   object
dtypes: object(1)
memory usage: 8.3+ KB


In [7]:
len(location_data)

1043

In [8]:
# It will show the count of unique values
location_data.nunique()

296

In [9]:
type(location_data.nunique())

int

In [10]:
# It will show the content of unique data ( will fetch the unique data set)
location_data.unique()

array(['Location 3', 'Location 6', 'Location 8', 'Location 26',
       'Location 34', 'Location 25', 'Location 46', 'Location 156',
       'Location 21', 'Location 13', 'Location 579', 'Location 602',
       'Location 10', 'Location 44', 'Location 30', 'Location 48',
       'Location 196', 'Location 64', 'Location 91', 'Location 62',
       'Location 75', 'Location 42', 'Location 233', 'Location 95',
       'Location 78', 'Location 61', 'Location 87', 'Location 19',
       'Location 115', 'Location 350', 'Location 377', 'Location 17',
       'Location 113', 'Location 81', 'Location 58', 'Location 212',
       'Location 53', 'Location 337', 'Location 41', 'Location 632',
       'Location 73', 'Location 214', 'Location 218', 'Location 38',
       'Location 172', 'Location 197', 'Location 101', 'Location 185',
       'Location 129', 'Location 235', 'Location 142', 'Location 50',
       'Location 76', 'Location 11', 'Location 33', 'Location 22',
       'Location 145', 'Location 203', 'Loca

In [11]:
type(location_data.unique())

numpy.ndarray

In [12]:
# Always use the "()" in those functions
location_data.unique

<bound method Series.unique of 0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object>

In [13]:
type(location_data.unique)

method

## Converting Series into Arrays

In [14]:
# .array will convert your series into a pandas array (An extension array)
# .to_numpy() will organize our info. into a pure NumPy array structure

In [15]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B' : 16600, 'Product C':15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [16]:
prices_per_category.values

array([22250, 16600, 15600], dtype=int64)

In [17]:
type(prices_per_category.values)

numpy.ndarray

In [18]:
prices_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [19]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [20]:
prices_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [21]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [22]:
test_array = prices_per_category[['Product A', 'Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [23]:
type(test_array[0])

numpy.float64

In [24]:
prices_per_category.values[0]

22250

In [25]:
type(prices_per_category.values[0])

numpy.int64

In [26]:
prices_per_category.array[0]

22250

In [27]:
type(prices_per_category.array[0])

numpy.int64

In [28]:
prices_per_category.to_numpy()[0]

22250

In [29]:
type(prices_per_category.to_numpy()[0])

numpy.int64

## Sort_values()

In [30]:
numbers = pd.Series([15,1000,23,45,444])
numbers

0      15
1    1000
2      23
3      45
4     444
dtype: int64

In [31]:
numbers.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [32]:
numbers.sort_values(ascending= False) # True is by default

1    1000
4     444
3      45
2      23
0      15
dtype: int64

In [33]:
data = pd.read_csv('Location.csv', squeeze= True)
location_data = data.copy()
location_data.head()

C:\Users\Sourav Vishwakarma\AppData\Local\Temp\ipykernel_6880\4004024906.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  data = pd.read_csv('Location.csv', squeeze= True)


0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [34]:
location_data.sort_values()

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [35]:
location_data.sort_values(ascending= False)

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

## Attribute and Method Chaining

In [36]:
# Attribute Chaining allows us to sequentially refer to the values obtained by the different attributes
# Method Chaining :
# - Organizes and applies several method calls on a certain object in a given order
# - each call performs its action and returns an intermediate output
# - Every next method from the chain respects the value returned by the previous one
# NOTE : it is not required to explicitly store any result or output or values.

In [37]:
import pandas as pd

In [38]:
data = pd.read_csv('Location.csv', squeeze= True)
location_data = data.copy()
location_data.head()

C:\Users\Sourav Vishwakarma\AppData\Local\Temp\ipykernel_6880\4004024906.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  data = pd.read_csv('Location.csv', squeeze= True)


0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [39]:
location_data.index

RangeIndex(start=0, stop=1043, step=1)

In [40]:
location_data.name

'Location'

In [41]:
location_data.index.name
# NO output driven because the range index object associated with the given series has NO name.
# The name we are reffering to here is different from the name of the series.

In [42]:
location_data.index.name = "Index"

In [43]:
location_data

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [44]:
location_data.index.name

'Index'

In [45]:
location_data.sort_values()

Index
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [46]:
location_data.sort_values().head()

Index
637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
Name: Location, dtype: object

In [47]:
location_data.index

RangeIndex(start=0, stop=1043, step=1, name='Index')

In [48]:
type(location_data.index)

pandas.core.indexes.range.RangeIndex

In [49]:
location_data.index.to_numpy()

array([   0,    1,    2, ..., 1040, 1041, 1042], dtype=int64)

## sort.Index()

Chaining Technique is vice versa with Assignment statments

In [50]:
#.sort_index() creates a temporary copy of the object's data it's been applied to and displays the output of its manupulation

In [51]:
data = pd.read_csv('Location.csv', squeeze= True)
location_data = data.copy()
location_data.head()

C:\Users\Sourav Vishwakarma\AppData\Local\Temp\ipykernel_6880\4004024906.py:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  data = pd.read_csv('Location.csv', squeeze= True)


0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [52]:
location_data.sort_values(ascending= False)

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [53]:
location_data_sv = location_data.sort_values(ascending= False)
location_data_sv.head()

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [54]:
location_data_sv.index

Int64Index([ 372,  757,  128,  482,  271,  669,  612,   29,  518,  598,
            ...
             904,  912, 1010,   14,  716,  202,  298,  637,  884,  465],
           dtype='int64', length=1043)

In [55]:
location_data_sv.index.sort_values()

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
           dtype='int64', length=1043)

In [56]:
# .sort_values() : Didn't overwrite the contents of location_data_sv
# .index.sort_values() : it is only useful if you need to obtain the sorted index structure
# as a separate entity for some reason.

In [57]:
location_data_sv.index = location_data_sv.index.sort_values()

In [58]:
location_data_sv

0       Location 99
1       Location 98
2       Location 97
3       Location 97
4       Location 97
           ...     
1038    Location 10
1039    Location 10
1040     Location 1
1041     Location 1
1042     Location 1
Name: Location, Length: 1043, dtype: object

In [59]:
location_data_sv = location_data.sort_values(ascending= False)
location_data_sv.head()

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [60]:
location_data_sv.sort_index()

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [61]:
location_data_sv

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [62]:
location_data_sv = location_data_sv.sort_index(ascending= True)
location_data_sv

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object