## An Introduction

In [1]:
#Matrix in Python - Collection of numbers present in ordered rows and columns

## Arrays in Python - the simplest way to work with matrices

In [2]:
import numpy as np

In [3]:
#Declare a Scalar

In [4]:
s= 5

In [5]:
s

5

In [6]:
#Declare a vector

In [7]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

In [8]:
#Declare a matrix

In [9]:
m = np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [10]:
#Data Types

In [11]:
type(s)

int

In [12]:
type(v)

numpy.ndarray

In [13]:
type(m)

numpy.ndarray

In [14]:
s_array = np.array(5)
s_array

array(5)

In [15]:
type(s_array)

numpy.ndarray

In [16]:
#Data Shapes

In [17]:
m.shape

(2, 3)

In [18]:
v.shape

(3,)

In [19]:
s_array.shape

()

In [20]:
# To create a row and column vector we can use the reshape function which gives a new shape without changing the data

In [21]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [22]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [23]:
s_array.shape

()

## What is Tensors

In [24]:
#Tensors are simply a generalization of the concepts we have seen so far

In [25]:
# Tensors can be stored in ndarrays


In [26]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [28]:
t = np.array([m1,m2])

In [29]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [30]:
#Checking the shape

In [31]:
type(t)

numpy.ndarray

In [32]:
t.shape

(2, 2, 3)

## Addition and Subtraction in Matrix

In [33]:
#Addition/Subtraction - condiiton : matrices have the same dimensions

In [34]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [36]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [37]:
# Same we can do for float values as well

In [40]:
m3 = np.array([[22.33,-4.73],[-203.14, 1200.02],[4.22,234.10]])
m3

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [41]:
m4 = np.array([[133.13,448.29],[-340.21,1.06],[30.41,424.99]])
m4

array([[ 133.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [42]:
m3-m4

array([[-110.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

In [43]:
#Adding Vectors - keep the length of vector same for both vectors to add or subtract

In [45]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [46]:
v2 = np.array([9,8,7,6,5])
v2

array([9, 8, 7, 6, 5])

In [47]:
v1+v2

array([10, 10, 10, 10, 10])

In [48]:
v1-v2

array([-8, -6, -4, -2,  0])

In [49]:
#ERRORS when adding matrices

In [50]:
m1+m3

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [51]:
#Exceptions (Adding with scalar)

In [52]:
m1+1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [53]:
v1+2

array([3, 4, 5, 6, 7])

## Transpose of Matrix

In [55]:
#Transposing vectors:
# The values are not changing or transforming, only their position is
#Transposing the same vector twice yields the initial vector(object)
# A 3x1 matrix transposed is a a 1x3 matrix
# Same applies to matrix 3x2 become 2x3 matrix

In [56]:
A = np.array([[5,12,6],[-3,0,14]])

In [57]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [58]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [59]:
B = np.array([[5,-3],[-2,4]])
B

array([[ 5, -3],
       [-2,  4]])

In [60]:
B.T

array([[ 5, -2],
       [-3,  4]])

In [61]:
x = np.array([1,2,3,4])

In [62]:
x.T


array([1, 2, 3, 4])

In [63]:
x

array([1, 2, 3, 4])

In [64]:
x.shape

(4,)

In [66]:
x.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

## Dot Products of Vectors

In [68]:
# Dot product of 2 vectors is a scalar
# Dot product also called as scalar product
# Dot product means SUM of the corresponding product element

In [69]:
x= np.array([2,8,-7])
y = np.array([1,-7,3])

In [70]:
np.dot(x,y)

-75

In [71]:
# Multiply scalar x vector

In [72]:
x


array([ 2,  8, -7])

In [73]:
x*5

array([ 10,  40, -35])

## Dot products of Matrices

In [75]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [77]:
# We can only multiply an mxn with an nxk matrix
# if we multiply mxn matrix with nxk matrix, result will be in mxk matrix

In [78]:
B

array([[ 5, -3],
       [-2,  4]])

In [80]:
C = np.array([[2,-1],[8,0],[3,0]])

In [81]:
C

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [82]:
np.dot(A,C)

array([[124,  -5],
       [ 36,   3]])

In [85]:
# Applications is data science: 
# Vectorized code
# Image recognition
# Dimensionality Reduction