## Indexing in NumPy

In [1]:
import numpy as np

In [2]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# We use indices to refer to the individual elements within an array
# Coordinates that help us navigate through the array
# Integers  array_a[0] --> 1st position = index 0

In [4]:
array_a[0]

array([1, 2, 3])

In [5]:
# To Fech each value
array_a[0][2]

3

In [6]:
# Another way which is widely used
array_a[0,2]

3

In [7]:
array_a[:,1]

array([2, 5])

In [8]:
# Negative indices means traversing the array backwards
array_b = np.array([1,2,3])
array_b

array([1, 2, 3])

In [9]:
array_b[-1]

3

In [10]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
array_a[-1]

array([4, 5, 6])

In [12]:
array_a[:,-1]

array([3, 6])

## Assigning values in NumPy

In [13]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [15]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [16]:
array_a[:,0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [17]:
list_a = [8,7,6]
array_a[0] = list_a
array_a

array([[8, 7, 6],
       [9, 5, 6]])

In [18]:
type(array_a[0])

numpy.ndarray

In [19]:
# Change all the values using single value   , NOTE : [:] is required to change all elements
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

## Elementwise Properties of Arrays

In [20]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [21]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array_a + 2

array([ 9, 10, 11])

In [23]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [24]:
# Lists Vs Arrays 
# Lists - The main purpose for lists is to store the data
# Array - The main purpose of arrays is to compute mathematical operations

In [25]:
array_a + array_b[0]

array([ 8, 10, 12])

In [26]:
# Elementwise addition
array_a[1] + array_b[0,1]

10

In [27]:
# Conditions : length of the 1-D array must match the "length" of the 2-D array to compute Mathematical operations

In [28]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

## Data Types supported in NumPy`

In [29]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = "float32")
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [30]:
# np.data_type = "data_type"  ex. dtype = "float32" OR dtype = np.float32

In [31]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = "complex64")
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [32]:
#BOOLEAN
array_a = np.array([[1,2,0],[4,5,6]], dtype = "bool")
array_a

array([[ True,  True, False],
       [ True,  True,  True]])

In [33]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = "str")
array_a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

## Characteristics of NumPy Functions

In [34]:
#Universal Functions : 
# Work with NDarrays on an element by element bases
# An extension of the elementwise operation
# mathematical operations, trignometric functions, comparison functions
# Ex. Broadcasting , Typecasting, computing over a given axis

In [35]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [36]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [37]:
matrix_C = np.array([[1,2,3],[4,5,6]])
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# Broadcasting
np.add(array_b, matrix_C)

## Adding up values, even though the arrays don't have matching shapes. 
# The function compiles if the sizes of the two variable are broadcastable

array([[2, 3, 4],
       [6, 7, 8]])

In [39]:
# RULES of Boradcasting :
# 1. The array have the same shape
# 2. The array have same dimensions, and the length of each dimension either common or 1
# 3. The arrays that have too few dimensions can have their shapes alloted with a dimension 1, to satisfy 2nd rule.

In [40]:
#Typecasting
# Taking evey element of an array and changing it to a specified datatype.
# Example : Changing the Whole number to decimal

In [41]:
np.add(array_b, matrix_C, dtype = np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

In [42]:
# Running over an Axis
# Numpy breaks down NDarray into smaller arrays of (N-1) - Many Dimensions
# Applies the function to each one
# We can use this feature to run a function along each row and column

In [43]:
np.mean(matrix_C, axis = 0) # --> axis = 0 means the mean for each COLUMN of the array

array([2.5, 3.5, 4.5])

In [44]:
matrix_C  # --> (1+4)/2 = 2.5 and so on

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.mean(matrix_C, axis = 1) # --> axis = 1 means the mean for each ROW of the array

array([2., 5.])

In [46]:
matrix_C  # --> (1+2+3)/3 = 2.0 and so on

array([[1, 2, 3],
       [4, 5, 6]])