## ndarrays

In [1]:
import numpy as np

In [2]:
# Originate from Numpy package
# A special datatype in Python
# Can store multiple numeric values in sequence
# Elementwise properties

In [3]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [4]:
type(array_a)

numpy.ndarray

In [5]:
# Array Vs ndarray
# Array --> Name of the function
# ndarray -- > object

In [6]:
array_a.shape #-- > (3,) can be read out like 3,",".

(3,)

In [7]:
array_b = np.array([[7,8,9],[10,11,12]])
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [8]:
type(array_b)

numpy.ndarray

In [9]:
print(array_b)  # --> 2X3 table

[[ 7  8  9]
 [10 11 12]]


In [10]:
array_b.shape

(2, 3)

In [11]:
# NOTE : ROWS --> 1st Dimension  , COLUMNS --> 2nd Dimension

In [12]:
array_c =np.array([13])

In [13]:
type(array_c)

numpy.ndarray

In [14]:
print(array_c)

[13]


In [15]:
array_c.shape

(1,)

## Arrays VS Lists

In [16]:
#list_a = [[1,2,3,4,5,6]]
list_a = [[1,2,3],[4,5,6]]

## Syntax for creating lists is similar to syntax for creating arrays.

In [17]:
array_a = np.array(list_a)

In [18]:
type(list_a)

list

In [19]:
type(array_a)

numpy.ndarray

In [20]:
array_a.shape

(2, 3)

In [21]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [22]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [23]:
# list_a.shape results in an error because lists don't have a shape.
#len(list_a)

len(list_a[1])

# We can use indexing to refer to a specific sublists out of a list. 

3

In [24]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [25]:
print(list_b)
# The primary purpose of lists is to store data, so list_b concatenates the rows of list_a.

[1, 2, 3, 4, 5, 6]


In [26]:
print(array_b)
# The primary purpose of arrays is computational, so array_b adds the values elementwise.

[5 7 9]


In [27]:
import math
array_e = math.sqrt(array_a[1,0])
print(array_e)

2.0


In [28]:
np.sqrt(array_a) 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## String Vs Object Vs Numbers

In [29]:
lending_co_lt = np.genfromtxt('lending-co-LT.csv', delimiter = ',', dtype = np.int32)
lending_co_lt

array([[   -1,    -1,    -1, ...,    -1,    -1,    -1],
       [    1,    -1,    -1, ...,    -1,    -1, 16600],
       [    2,    -1,    -1, ...,    -1,    -1, 16600],
       ...,
       [ 1041,    -1,    -1, ...,    -1,    -1, 16600],
       [ 1042,    -1,    -1, ...,    -1,    -1, 15600],
       [ 1043,    -1,    -1, ...,    -1,    -1, 16600]])

In [30]:
print(lending_co_lt)

[[   -1    -1    -1 ...    -1    -1    -1]
 [    1    -1    -1 ...    -1    -1 16600]
 [    2    -1    -1 ...    -1    -1 16600]
 ...
 [ 1041    -1    -1 ...    -1    -1 16600]
 [ 1042    -1    -1 ...    -1    -1 15600]
 [ 1043    -1    -1 ...    -1    -1 16600]]


In [31]:
lending_co_lt[0,0] + lending_co_lt[0,1]

-2

In [32]:
lending_co_lt = np.genfromtxt('lending-co-LT.csv', delimiter = ',', dtype = np.str)

C:\Users\Sourav Vishwakarma\AppData\Local\Temp\ipykernel_14656\3324726678.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_lt = np.genfromtxt('lending-co-LT.csv', delimiter = ',', dtype = np.str)


In [33]:
print(lending_co_lt)

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


In [34]:
lending_co_lt = np.genfromtxt('lending-co-LT.csv', delimiter = ',', dtype = np.object)
print(lending_co_lt)

[[b'LoanID' b'StringID' b'Product' ... b'Location' b'Region'
  b'TotalPrice']
 [b'1' b'id_1' b'Product B' ... b'Location 2' b'Region 2' b'16600.0']
 [b'2' b'id_2' b'Product B' ... b'Location 3' b'' b'16600.0']
 ...
 [b'1041' b'id_1041' b'Product B' ... b'Location 23' b'Region 4'
  b'16600.0']
 [b'1042' b'id_1042' b'Product C' ... b'Location 52' b'Region 6'
  b'15600.0']
 [b'1043' b'id_1043' b'Product B' ... b'Location 142' b'Region 6'
  b'16600.0']]


C:\Users\Sourav Vishwakarma\AppData\Local\Temp\ipykernel_14656\1213456919.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lending_co_lt = np.genfromtxt('lending-co-LT.csv', delimiter = ',', dtype = np.object)
