## Basic slicing in NumPy

In [1]:
import numpy as np

In [2]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# Slicing - Creating a new array by taking chunks of values out of an existing one
# it can contain either orignal row and column or just parts of them

In [4]:
matrix_A[0:0]  #--> its will give a 0-D array

array([], shape=(0, 3), dtype=int32)

In [5]:
matrix_A[0:1]

array([[1, 2, 3]])

In [6]:
type(matrix_A[0:1])

numpy.ndarray

In [7]:
matrix_A[1:]

array([[4, 5, 6]])

In [8]:
matrix_A[2:]  # --> since its only contain 2 rows ,it returns and emty array

array([], shape=(0, 3), dtype=int32)

In [9]:
# matrix_A[n:] and matrix_A[:n] are complementary slices
# Indexing is very similar to slicing 
# Indexing = specific indexing
# Sliciing = interval indexing

In [10]:
matrix_A[1]

array([4, 5, 6])

In [11]:
matrix_A[:-1]

array([[1, 2, 3]])

In [12]:
matrix_A[:,1:]

array([[2, 3],
       [5, 6]])

In [13]:
matrix_A[1:,1:]

array([[5, 6]])

## Stepwise slicing in NumPy

In [14]:
# Stepwise slicing - Slicing, Where we don't take consecutive values
# Values which are a certain distance apart
# Example : matrix[1:10:3,:] --> rows will get sliced starting with 1 ending with 10 and step = 3

In [15]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [16]:
matrix_B[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [17]:
matrix_B[-1::-1,::2]

# The syntax for each dimension is "[start : stop : step]". 
# A negative step means we're going through the array in reverse.

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

In [18]:
matrix_B[::-2,::2]

array([[4, 3, 0],
       [1, 1, 0]])

## Conditional Slicing in NumPy

In [19]:
matrix_C = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [20]:
matrix_C[:,0]

array([1, 3, 4])

In [21]:
matrix_C[:,0] > 2

# Returns True/False based on whether the individual element satisfies the condition. 

array([False,  True,  True])

In [22]:
matrix_C[:,:] > 2

# Returns True/False based on whether the individual element satisfies the condition. 

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [23]:
matrix_C[matrix_C[:,:] > 2]
# Resone why the output is 1D array - 
# NumPy doesn't know how many of the elements would fit this condition
# Python take flattened array(1-D) and applies the condition on it.

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [24]:
matrix_C[matrix_C[:,:] % 2 == 0]

# Returns the actual values which satisfy the condition, not simply True or False.

array([2, 0, 6, 6, 4, 4, 8, 0])

In [25]:
matrix_C[(matrix_C[:,:] % 2 == 0) | (matrix_C[:,:] <= 4)]

# We can have more complex conditions, which are comprised of several smaller conditions. 
# & -> Both conditions must be met. 
# | -> Either condition can be met. 

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

## Dimension and Squeeze Funtion in NumPy

In [26]:
matrix_D = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [27]:
type(matrix_D[0,0])

# Fixing both indices. 
# 0-D array

numpy.int32

In [28]:
print(matrix_D[0,0])

1


In [29]:
type(matrix_D[0,0:1])

numpy.ndarray

In [30]:
print(matrix_D[0,0:1])

[1]


In [31]:
type(matrix_D[0:1,0:1])

# Both indices are ranges (slices)
# 2-D array

numpy.ndarray

In [32]:
print(matrix_D[0:1,0:1])

[[1]]


In [33]:
print(matrix_D[0,0].shape)    #-->scalar
print(matrix_D[0,0:1].shape)  # --> Vector
print(matrix_D[0:1,0:1].shape) # --> Matrix

# Same value stored in 3 different ways -> 0-D, 1-D and 2-D array

()
(1,)
(1, 1)


In [34]:
#Squeeze Method - Removes all the unnecessary dimensions of an array
#[[1]] --> 1

In [35]:
print(matrix_D[0:1,0:1].squeeze())

## Removes excess dimensions

1


In [36]:
type(matrix_D[0:1,0:1].squeeze()) # --> it's a 0-D array

numpy.ndarray

In [37]:
matrix_D[0:1,0:1].squeeze().shape  # --> Squeezed array has no shape (0-D Array)

()

In [38]:
np.squeeze(matrix_D[0:1,0:1])

## The function is equivalent to the method. 

array(1)

In [39]:
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

## All excess dimensions are lost and our outputs are aligned. 

()
()
()


# *****END*****